START_COMMAND = "Hey! Welcome to innit bot. Innitbot helps you to track all the tweets that you want. Enter Your Token ID to go further!"
EXIST_TOKEN = """SELECT token_id,telegram_chat_id FROM innit.telegram_user_token WHERE telegram_chat_id = '{db_chat_id}' AND token_id = '{db_token_id}'"""
PUSH_USER_DATA = """INSERT INTO innit.telegram_user_token (telegram_chat_id,token_id) VALUES ('{chat_id}','{db_token_id}')"""
GET_ALL_USER = """SELECT telegram_chat_id from innit.telegram_user_token WHERE token_id='{db_token_id}'"""
ALL_TOKEN_QUERY = """SELECT token_id FROM innit.telegram_user_token where telegram_chat_id = '{chat_id}'"""
DELETE_ONE_TOKEN = """DELETE FROM innit.telegram_user_token WHERE telegram_chat_id = '{db_chat_id}' AND token_id = '{db_token_id}'"""
DELETE_DATA_QUERY = """DELETE FROM innit.telegram_user_token WHERE telegram_chat_id = '{chat_id}'"""
LIST_QUERY = """SELECT token_id FROM innit.telegram_user_token WHERE telegram_chat_id = '{chat_id}'"""
